### ISSUE TITLE
iNat occurrence feature image should be in the BIE image gallery

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/bie-plugin#247] opened 2021-06-11 00:58 UTC
Feedback from iNaturalist user about images and how they end up in the species gallery in the BIE:

![image](https://user-images.githubusercontent.com/1271932/121458330-807be480-c9ec-11eb-9dab-f736205f6e05.png)

From this record:
https://biocache.ala.org.au/occurrences/10cbb1ff-26fa-4f82-a2ed-4e3196054ba3
https://www.inaturalist.org/observations/66990199

The images are sorted in a production biocache record by a different order to how they are sorted in iNaturalist. This sort order is important in iNaturalist and it's not related to the date taken. 

Production records
id | order on record page | date taken
-- | -- | --
181222eb-fbe2-442c-99f9-2c9d0cf2d531 | 1 | 25 Dec, 2020 00:09:57 (this is the one that went to the BIE)
29f72521-4f1a-48eb-b174-859ec9e4be61 | 2 | 25 Dec, 2020 00:10:39
2ec6b358-fd91-475b-9afb-721dc5bef00b | 3 | 25 Dec, 2020 00:08:33
4ef2829c-1bf6-4726-8b07-cb016a99bc78 | 4 | 25 Dec, 2020 00:09:20
6c5b7619-2b21-471a-a1af-a677c26efaf5 | 5 | 25 Dec, 2020 00:10:03

How can we ensure the "first" inaturalist image can get across to BIE now?

**Comment by TaniaGLaity** [comment] 2023-11-06 23:49
closed - duplicate of [ala-bie-hub #84](https://github.com/AtlasOfLivingAustralia/ala-bie-hub/issues/84) - content from the above issue copied accross

**Closed by TaniaGLaity** 2023-11-06 23:49 UTC
