### ISSUE TITLE
Link indigenous names to their Profiles page

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-plugin#246] opened 2021-05-19 04:17 UTC
This feature needs to be implemented with a feature flag, so we can turn it on, after a certain date (beginning of August 2021) but deploy the changes before then.

We need to link indigenous names back to their source Profiles page, so name should be a simple hyperlink.  Ideally an identifier will be provided from the Profiles system, when feeding names into the BIE index. We should then be able to use this identifier to generate a link to the Profiles page. 

Indigenous name will need to provide data from Profiles about whether the page is publically viewable or not and thus only generate links for public (Profiles) pages.

@NatRB  also wants a separate change to remove the duplicate names from species pages, and only show them on the linked Profiles page - just a heads-up to remember this and create a new issue for it.

CC @elywallis @peggynewman

**Comment by nickdos** [comment] 2021-07-13 00:36
@charvolant Could you check with @temi to see if a test version of Profiles has the new API that would allow BIE to index the IEK names and whether their profile page is public and to get the URL to the Profile. So that we can link IEK names on species pages to their Profile page.

**Comment by TaniaGLaity** [comment] 2023-12-06 05:29
closing duplicate of issue #https://github.com/AtlasOfLivingAustralia/ux-ui/issues/236

**Closed by TaniaGLaity** 2023-12-06 05:29 UTC
Labels: enhancement, Names
