### ISSUE TITLE
Suggested improvements from Alexis

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-plugin#10] opened 2016-02-09 03:17 UTC
> From: "Tindall, Alexis (SAM)" Alexis.Tindall@samuseum.sa.gov.au
> Date: Tuesday, 9 February 2016 at 2:11 PM
> To: Nick Nick.Dosremedios@csiro.au
> Cc: "Ryonen.Butcher@DPaW.wa.gov.au" Ryonen.Butcher@DPaW.wa.gov.au
> Subject: RE: Query about your work on ALA search functionality
> 
> Hi Nick,
> 
> Apologies for taking some time to get back to you. Thanks for this. I’ve had an opportunity to look at the Atlas of Living Scotland now, and it looks very slick.
> 
> I trust that you know what you’re doing when it comes to the code and searching under names – I don’t think I can offer any advice in that area! The only bit of feedback that might be related to searching is the suggestion I made recently that gallery views of images might be better organised if they were sorted by genus or something similar, that would be more useful. I did add that suggestion to github some time ago, but I can’t find the issue now.  
> 
> The species page layout is very appealing on the Atlas of Living Scotland. I think that the ALA species pages could do with a makeover. I think that the display of information from Species Lists on the pages is usually a bit baffling to the average visitor. Unfortunately the really good, readable information from the field guides project is lost among the other information that is provided, and the categories, codes and other material that fits around that information is not clear to the reader at all.
> 
> I also know from my own colleagues that unfortunately they have struggled to tell the difference between a distribution map and an occurrence records map – perhaps we could consider an explanatory caption or hover text if we are thinking about a re-jig to species pages.
> 
> Thanks for the info, good luck with the re-write!
> Alexis

**Comment by TaniaGLaity** [comment] 2023-12-06 04:57
closing as outstanding issue in the above is duplicate of issue # https://github.com/AtlasOfLivingAustralia/ala-bie-hub/issues/92

**Closed by TaniaGLaity** 2023-12-06 04:57 UTC
